format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#1793D1)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$python\
$java\
$ruby\
$c\
$cpp\
$haskell\
$kotlin\
[](fg:#212736 bg:#1d2230)\
$cmd_duration\
$time\
[ ](fg:#1d2230)\
\n$character"""

[cmd_duration]
format = '[[ ⏱️ $duration ](fg:#a0a9cb bg:#1d2230)]($style)' 
min_time =  60_000  # Minimum time in milliseconds to display duration
style = "bg:#1d2230" 

[directory]
format = "[ $path ]($style)"
style = "fg:#e3e5e5 bg:#769ff0"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"
symbol = ""

[git_status]
format = '[[($all_status$ahead_behind $count )](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"
modified = "~${count}"
staged = "+${count}"
untracked = "?${count}"
deleted = "-${count}"
conflicted = "!${count}"


[nodejs]
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
style = "bg:#212736"
symbol = ""

[rust]
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
style = "bg:#212736"
symbol = ""

[golang]
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
style = "bg:#212736"
symbol = ""

[php]
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
style = "bg:#212736"
symbol = ""

[java]
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'
style = "bg:green"
symbol = " "

[kotlin]
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'
style = "bg:green"
symbol = ""

[haskell]
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'
style = "bg:green"
symbol = ""

[python]
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'
style = "bg:green"
symbol = ""

[c]
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'
style = "bg:green"
symbol = " "

[cpp]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = " "

[time]
disabled = false 
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)' 
style = "bg:#1d2230" 
time_format = "%R" # Hour:Minute Format

